// Mock data for local development - no database required!

// Mock categories for events
export const MOCK_CATEGORIES = [
    {
        id: 'cat-1',
        name: 'dining',
        displayNameEn: 'Dining',
        displayNameFr: 'Gastronomie',
        slug: 'dining',
        description: 'Food festivals, wine tastings, and culinary experiences',
        icon: 'utensils',
        color: '#f97316',
        sortOrder: 0,
        published: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        eventCount: 1
    },
    {
        id: 'cat-2',
        name: 'exhibition',
        displayNameEn: 'Exhibitions',
        displayNameFr: 'Expositions',
        slug: 'exhibitions',
        description: 'Art exhibitions, gallery shows, and cultural displays',
        icon: 'image',
        color: '#8b5cf6',
        sortOrder: 1,
        published: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        eventCount: 2
    },
    {
        id: 'cat-3',
        name: 'workshop',
        displayNameEn: 'Workshops',
        displayNameFr: 'Ateliers',
        slug: 'workshops',
        description: 'Hands-on learning experiences and educational sessions',
        icon: 'wrench',
        color: '#06b6d4',
        sortOrder: 2,
        published: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        eventCount: 1
    },
    {
        id: 'cat-4',
        name: 'performance',
        displayNameEn: 'Performances',
        displayNameFr: 'Performances',
        slug: 'performances',
        description: 'Live music, theater, and entertainment shows',
        icon: 'music',
        color: '#ec4899',
        sortOrder: 3,
        published: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        eventCount: 1
    },
    {
        id: 'cat-5',
        name: 'sports',
        displayNameEn: 'Sports',
        displayNameFr: 'Sports',
        slug: 'sports',
        description: 'Athletic events, competitions, and fitness activities',
        icon: 'trophy',
        color: '#22c55e',
        sortOrder: 4,
        published: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        eventCount: 1
    }
];

// Mock categories for talents
export const MOCK_TALENT_CATEGORIES = [
    {
        id: 'talent-cat-1',
        name: 'visual-arts',
        displayNameEn: 'Visual Arts',
        displayNameFr: 'Arts visuels',
        slug: 'visual-arts',
        description: 'Painters, sculptors, photographers, and digital artists',
        icon: 'palette',
        color: '#8b5cf6',
        sortOrder: 0,
        published: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        talentCount: 1
    },
    {
        id: 'talent-cat-2',
        name: 'design',
        displayNameEn: 'Design',
        displayNameFr: 'Design',
        slug: 'design',
        description: 'Graphic, industrial, fashion, and UX designers',
        icon: 'pen-tool',
        color: '#f97316',
        sortOrder: 1,
        published: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        talentCount: 1
    },
    {
        id: 'talent-cat-3',
        name: 'culinary',
        displayNameEn: 'Culinary',
        displayNameFr: 'Culinaire',
        slug: 'culinary',
        description: 'Chefs, bakers, and culinary artists',
        icon: 'chef-hat',
        color: '#ec4899',
        sortOrder: 2,
        published: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        talentCount: 1
    },
    {
        id: 'talent-cat-4',
        name: 'music',
        displayNameEn: 'Music',
        displayNameFr: 'Musique',
        slug: 'music',
        description: 'Musicians, composers, and vocalists',
        icon: 'music',
        color: '#22c55e',
        sortOrder: 3,
        published: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        talentCount: 1
    },
    {
        id: 'talent-cat-5',
        name: 'performance',
        displayNameEn: 'Performance',
        displayNameFr: 'Performance',
        slug: 'performance',
        description: 'Actors, dancers, and performing artists',
        icon: 'masks-theater',
        color: '#06b6d4',
        sortOrder: 4,
        published: true,
        createdAt: new Date(),
        updatedAt: new Date(),
        talentCount: 1
    }
];

// Helper to create a mock media object
function createMockMedia(url: string, type: 'image' | 'video' = 'image') {
    return {
        id: `mock-media-${Math.random().toString(36).substr(2, 9)}`,
        type,
        url,
        s3Key: `mock/${url.split('/').pop()}`,
        mimeType: type === 'image' ? 'image/jpeg' : 'video/mp4',
        size: 1234567,
        eventId: null as string | null,
        talentId: null as string | null,
        isCover: false,
        createdAt: new Date()
    };
}

export const MOCK_EVENTS = [
    {
        id: '1',
        titleEn: 'Summer Music Festival 2026',
        titleFr: 'Festival de Musique d\'Été 2026',
        slug: 'summer-music-festival-2026',
        descriptionEn: 'Join us for an unforgettable night of live music featuring local and international artists. Experience a magical evening under the stars with food trucks, craft beer, and amazing vibes. This year\'s lineup includes Grammy-nominated performers, emerging indie artists, and special surprise guests. The festival showcases diverse genres from rock and indie to electronic and world music. With multiple stages, interactive art installations, and a vibrant atmosphere, this is the must-attend event of the summer. Bring your friends, family, and dancing shoes for a celebration of music, community, and unforgettable moments.',
        descriptionFr: 'Rejoignez-nous pour une soirée inoubliable de musique live avec des artistes locaux et internationaux. Vivez une soirée magique sous les étoiles avec des food trucks, des bières artisanales et une ambiance incroyable. Le programme de cette année comprend des artistes nominés aux Grammy, des artistes indie émergents et des invités surprise. Le festival présente des genres variés allant du rock à l\'indie en passant par l\'electronic et la musique du monde. Avec plusieurs scènes, des installations artistiques interactives et une ambiance vibrante, c\'est l\'événement incontournable de l\'été. Apportez vos amis, votre famille et vos chaussures de danse pour une célébration de la musique, de la communauté et de moments inoubliables.',
        subtitleEn: 'A celebration of sound under the stars with world-class performers and local talent',
        subtitleFr: 'Une célébration du son sous les étoiles avec des artistes de classe mondiale et des talents locaux',
        startDate: new Date('2026-07-15T18:00:00Z'),
        endDate: new Date('2026-07-15T23:00:00Z'),
        locationEn: 'Central Park, New York',
        locationFr: 'Central Park, New York',
        venueNameEn: 'Central Park Great Lawn',
        venueNameFr: 'Central Park Great Lawn',
        streetAddressEn: 'Mid-Park at 79th Street',
        streetAddressFr: 'Mid-Park at 79th Street',
        districtEn: 'Manhattan',
        districtFr: 'Manhattan',
        cityEn: 'New York',
        cityFr: 'New York',
        postalCode: '10024',
        countryEn: 'USA',
        countryFr: 'États-Unis',
        collaborators: JSON.stringify([
            { name: 'Electric Dreams Productions', role: 'Event Production' },
            { name: 'Sarah Martinez', role: 'Musical Director' }
        ]),
        timings: JSON.stringify([
            { label: 'Gates Open', time: '17:00' },
            { label: 'Main Stage', time: '18:00 - 23:00' },
            { label: 'Indie Stage', time: '18:30 - 22:30' }
        ]),
        curatorEn: 'Michael Chen',
        curatorFr: 'Michael Chen',
        materialsEn: 'Live Stage, Sound Systems, Lighting',
        materialsFr: 'Scène live, systèmes de son, éclairage',
        admissionInfoEn: '$45 General Admission, $120 VIP',
        admissionInfoFr: '45 $ entrée générale, 120 $ VIP',
        published: true,
        isSpotlight: true,
        categoryId: 'cat-4',
        category: MOCK_CATEGORIES[3],
        createdAt: new Date(),
        updatedAt: new Date(),
        coverMediaId: 'mock-cover-1',
        coverMedia: createMockMedia("https://hoirqrkdgbmvpwutwuwj.supabase.co/storage/v1/object/public/assets/assets/917d6f93-fb36-439a-8c48-884b67b35381_1600w.jpg"),
        media: [],
    },
    {
        id: '2',
        titleEn: 'Tech Innovation Summit',
        titleFr: 'Sommet sur l\'Innovation Technologique',
        slug: 'tech-innovation-summit',
        descriptionEn: 'Explore the latest in technology and innovation with industry leaders. Network with fellow tech enthusiasts and learn about cutting-edge developments in AI, blockchain, and more. This three-day summit features keynote speakers from top tech companies, hands-on workshops, and exclusive product launches. Whether you\'re a developer, entrepreneur, or investor, you\'ll find valuable insights and opportunities to connect with pioneers shaping the future of technology.',
        descriptionFr: 'Explorez les dernières technologies et innovations avec des leaders de l\'industrie. Rencontrez des passionnés de technologie et découvrez les développements de pointe en IA, blockchain, et plus encore. Ce sommet de trois jours features des conférenciers principaux de grandes entreprises technologiques, des ateliers pratiques et des lancements de produits exclusifs. Que vous soyez développeur, entrepreneur ou investisseur, vous trouverez des précieux insights et des opportunités de vous connecter avec des pionniers façonnant l\'avenir de la technologie.',
        subtitleEn: 'Exploring the future of technology with industry pioneers and visionaries',
        subtitleFr: 'Explorer l\'avenir de la technologie avec des pionniers et visionnaires de l\'industrie',
        startDate: new Date('2026-09-20T09:00:00Z'),
        endDate: new Date('2026-09-22T17:00:00Z'),
        locationEn: 'San Francisco Convention Center',
        locationFr: 'Centre de Conventions de San Francisco',
        venueNameEn: 'Moscone Convention Center',
        venueNameFr: 'Centre de Conventions Moscone',
        streetAddressEn: '747 Howard St',
        streetAddressFr: '747 Howard St',
        districtEn: 'SoMa',
        districtFr: 'SoMa',
        cityEn: 'San Francisco',
        cityFr: 'San Francisco',
        postalCode: '94103',
        countryEn: 'USA',
        countryFr: 'États-Unis',
        collaborators: JSON.stringify([
            { name: 'TechCorp', role: 'Sponsor' },
            { name: 'Dr. Emily Watson', role: 'Keynote Speaker' }
        ]),
        timings: JSON.stringify([
            { label: 'Registration', time: '08:00' },
            { label: 'Keynotes', time: '09:00 - 17:00' },
            { label: 'Networking', time: '18:00 - 20:00' }
        ]),
        curatorEn: 'Innovation Labs',
        curatorFr: 'Innovation Labs',
        materialsEn: 'Digital Displays, VR Demos, Interactive Exhibits',
        materialsFr: 'Écrans numériques, démos VR, expositions interactives',
        admissionInfoEn: '$299 Professional Pass, $899 All Access',
        admissionInfoFr: '299 $ pass professionnel, 899 $ tout accès',
        published: true,
        isSpotlight: false,
        categoryId: 'cat-3',
        category: MOCK_CATEGORIES[2],
        createdAt: new Date(),
        updatedAt: new Date(),
        coverMediaId: null,
        coverMedia: createMockMedia("https://images.unsplash.com/photo-1470723710355-95304d8aece4?q=80&w=2670&auto=format&fit=crop"),
        media: [
            createMockMedia("https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=2670&auto=format&fit=crop"),
            createMockMedia("https://images.unsplash.com/photo-1515187029135-18ee286d815b?q=80&w=2670&auto=format&fit=crop"),
            createMockMedia("https://images.unsplash.com/photo-1505373877841-8d25f7d46678?q=80&w=2560&auto=format&fit=crop"),
            createMockMedia("https://images.unsplash.com/photo-1475721027785-f74eccf877e2?q=80&w=2670&auto=format&fit=crop"),
        ],
    },
    {
        id: '3',
        titleEn: 'Art & Design Exhibition',
        titleFr: 'Exposition d\'Art et de Design',
        slug: 'art-design-exhibition',
        descriptionEn: 'A curated collection of contemporary art and design from emerging artists. Discover unique pieces and meet the creators behind stunning visual works. This exhibition brings together works from over 50 artists spanning multiple disciplines including painting, sculpture, digital art, and mixed media installations. Artist talks and guided tours are available throughout the exhibition period, offering deeper insights into the creative process and the themes explored in the works.',
        descriptionFr: 'Une collection sélectionnée d\'art et de design contemporains d\'artistes émergents. Découvrez des pièces uniques et rencontrez les créateurs derrière ces œuvres visuelles époustouflantes. Cette exposition réunit des œuvres de plus de 50 artistes couvrant plusieurs disciplines notamment la peinture, la sculpture, l\'art numérique et les installations mixtes. Des conférences d\'artistes et des visites guidées sont disponibles tout au long de la période d\'exposition, offrant des approfondissements sur le processus créatif et les thèmes explorés dans les œuvres.',
        subtitleEn: 'Contemporary perspectives on form, color, and digital expression',
        subtitleFr: 'Perspectives contemporaines sur la forme, la couleur et l\'expression numérique',
        startDate: new Date('2026-10-10T10:00:00Z'),
        endDate: new Date('2026-10-31T18:00:00Z'),
        locationEn: 'Modern Art Gallery, London',
        locationFr: "Galerie d'Art Moderne, Londres",
        venueNameEn: 'Tate Modern',
        venueNameFr: 'Tate Modern',
        streetAddressEn: 'Bankside',
        streetAddressFr: 'Bankside',
        districtEn: 'Southwark',
        districtFr: 'Southwark',
        cityEn: 'London',
        cityFr: 'Londres',
        postalCode: 'SE1 9TG',
        countryEn: 'UK',
        countryFr: 'Royaume-Uni',
        collaborators: JSON.stringify([
            { name: 'Emma Rodriguez', role: 'Featured Artist' },
            { name: 'Design Collective UK', role: 'Co-Curator' }
        ]),
        timings: JSON.stringify([
            { label: 'Gallery Hours', time: '10:00 - 18:00 (Daily)' },
            { label: 'Artist Talks', time: '14:00 (Weekends)' }
        ]),
        curatorEn: 'James Morrison',
        curatorFr: 'James Morrison',
        materialsEn: 'Mixed Media, Digital Art, Sculpture',
        materialsFr: 'Médias mixtes, art numérique, sculpture',
        admissionInfoEn: 'Free (Donations Welcome)',
        admissionInfoFr: 'Gratuit (Dons acceptés)',
        published: true,
        isSpotlight: false,
        categoryId: 'cat-2',
        category: MOCK_CATEGORIES[1],
        createdAt: new Date(),
        updatedAt: new Date(),
        coverMediaId: null,
        coverMedia: createMockMedia("https://images.unsplash.com/photo-1544531586-fde5298cdd40?q=80&w=2670&auto=format&fit=crop"),
        media: [
            createMockMedia("https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?q=80&w=2680&auto=format&fit=crop"),
            createMockMedia("https://images.unsplash.com/photo-1501084817091-a4f3d1d19e07?q=80&w=2670&auto=format&fit=crop"),
            createMockMedia("https://images.unsplash.com/photo-1518998053901-5348d3961a04?q=80&w=2574&auto=format&fit=crop"),
            createMockMedia("https://images.unsplash.com/photo-1549490349-8643362247b5?q=80&w=2574&auto=format&fit=crop"),
            createMockMedia("https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?q=80&w=2670&auto=format&fit=crop"),
        ],
    },
    {
        id: '4',
        titleEn: 'Food & Wine Tasting Festival',
        titleFr: 'Festival de Dégustation de Vin et de Cuisine',
        slug: 'food-wine-tasting-festival',
        descriptionEn: 'Indulge in a culinary journey featuring award-winning chefs and premium wines. Sample exquisite dishes and discover new flavors from around the world. This three-day festival celebrates the art of gastronomy with cooking demonstrations, wine pairing workshops, and exclusive tasting sessions. Meet celebrity chefs, learn secret recipes, and savor dishes prepared with locally-sourced ingredients. Perfect for food lovers, wine enthusiasts, and anyone who appreciates the finer things in life.',
        descriptionFr: 'Laissez-vous tenter par un voyage culinaire mettant en vedette des chefs primés et des vins premium. Goûtez à des plats exquis et découvrez de nouvelles saveurs du monde entier. Ce festival de trois jours célèbre l\'art de la gastronomie avec des démonstrations de cuisine, des ateliers d\'accords mets-vins et des séances de dégustation exclusives. Rencontrez des chefs célèbres, apprenez des recettes secrètes et savourez des plats préparés avec des ingrédients locaux. Idéal pour les amateurs de cuisine, les passionnés de vin et tous ceux qui apprécient les belles choses de la vie.',
        subtitleEn: 'A culinary journey through award-winning flavors and vintage selections',
        subtitleFr: 'Un voyage culinaire à travers des saveurs primées et des sélections vintage',
        startDate: new Date('2026-08-05T12:00:00Z'),
        endDate: new Date('2026-08-07T20:00:00Z'),
        locationEn: 'Napa Valley, California',
        locationFr: 'Vallée de Napa, Californie',
        venueNameEn: 'Napa Valley Expo',
        venueNameFr: 'Expo de la Vallée de Napa',
        streetAddressEn: '1435 First St',
        streetAddressFr: '1435 First St',
        districtEn: 'Napa',
        districtFr: 'Napa',
        cityEn: 'Napa',
        cityFr: 'Napa',
        postalCode: '94559',
        countryEn: 'USA',
        countryFr: 'États-Unis',
        collaborators: JSON.stringify([
            { name: 'Chef David Thompson', role: 'Culinary Director' },
            { name: 'Sommelier Lisa Chang', role: 'Wine Selection' }
        ]),
        timings: JSON.stringify([
            { label: 'Morning Session', time: '10:00 - 14:00' },
            { label: 'Evening Session', time: '17:00 - 21:00' }
        ]),
        curatorEn: 'Napa Culinary Institute',
        curatorFr: 'Institut Culinair de Napa',
        materialsEn: 'Tasting Stations, Wine Cellars, Chef Demos',
        materialsFr: 'Stations de dégustation, caves à vin, démonstrations de chefs',
        admissionInfoEn: '$85 Per Session, $150 Full Day',
        admissionInfoFr: '85 $ par séance, 150 $ journée complète',
        published: true,
        isSpotlight: false,
        categoryId: 'cat-1',
        category: MOCK_CATEGORIES[0],
        createdAt: new Date(),
        updatedAt: new Date(),
        coverMediaId: null,
        coverMedia: createMockMedia("https://images.unsplash.com/photo-1600607686527-6fb886090705?q=80&w=2500&auto=format&fit=crop"),
        media: [
            createMockMedia("https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=2670&auto=format&fit=crop"),
            createMockMedia("https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=2670&auto=format&fit=crop"),
            createMockMedia("https://images.unsplash.com/photo-1547592180-85f173990554?q=80&w=2670&auto=format&fit=crop"),
        ],
    },
    {
        id: '5',
        titleEn: 'Marathon for Charity',
        titleFr: 'Marathon Caritatif',
        slug: 'marathon-for-charity',
        descriptionEn: 'Run for a cause! Join thousands of runners in this annual charity marathon supporting children\'s education worldwide. The course winds through scenic neighborhoods and historic landmarks, with cheering spectators and entertainment at every mile. Whether you\'re a seasoned marathoner or a first-time runner, you\'ll find support, encouragement, and the satisfaction of making a difference. All proceeds go directly to building schools and providing educational resources in underserved communities.',
        descriptionFr: 'Courez pour une cause! Rejoignez des milliers de coureurs dans ce marathon caritatif annuel soutenant l\'éducation des enfants dans le monde. Le parcours serpente à travers des quartiers pittoresques et des monuments historiques, avec des spectateurs encourageants et des animations à chaque kilomètre. Que vous soyez un marathonien chevronné ou un coureur débutant, vous trouverez du soutien, de l\'encouragement et la satisfaction de faire une différence. Tous les profits vont directement à la construction d\'écoles et à la fourniture de ressources éducatives dans les communautés défavorisées.',
        subtitleEn: 'Running together for children\'s education and a brighter future',
        subtitleFr: 'Courons ensemble pour l\'éducation des enfants et un avenir meilleur',
        startDate: new Date('2026-11-15T06:00:00Z'),
        endDate: new Date('2026-11-15T14:00:00Z'),
        locationEn: 'Boston, Massachusetts',
        locationFr: 'Boston, Massachusetts',
        venueNameEn: 'Boston Marathon Route',
        venueNameFr: 'Parcours du Marathon de Boston',
        streetAddressEn: 'Hopkinton to Boston',
        streetAddressFr: 'Hopkinton à Boston',
        districtEn: 'Multiple',
        districtFr: 'Multiple',
        cityEn: 'Boston',
        cityFr: 'Boston',
        postalCode: '02108',
        countryEn: 'USA',
        countryFr: 'États-Unis',
        collaborators: JSON.stringify([
            { name: 'Global Education Fund', role: 'Beneficiary' },
            { name: 'Boston Athletic Club', role: 'Organizer' }
        ]),
        timings: JSON.stringify([
            { label: 'Registration', time: '05:00 - 06:00' },
            { label: 'Race Start', time: '06:30' },
            { label: 'Awards', time: '13:00' }
        ]),
        curatorEn: 'Boston Sports Foundation',
        curatorFr: 'Fondation des Sports de Boston',
        materialsEn: 'Running Track, Medical Stations, Timing Systems',
        materialsFr: 'Piste de course, postes médicaux, systèmes de chronométrage',
        admissionInfoEn: '$50 Registration Fee (includes t-shirt)',
        admissionInfoFr: '50 $ frais d\'inscription (t-shirt inclus)',
        published: true,
        isSpotlight: false,
        categoryId: 'cat-5',
        category: MOCK_CATEGORIES[4],
        createdAt: new Date(),
        updatedAt: new Date(),
        coverMediaId: null,
        coverMedia: createMockMedia("https://images.unsplash.com/photo-1519750783826-e2420f4d687f?q=80&w=2574&auto=format&fit=crop"),
        media: [
            createMockMedia("https://images.unsplash.com/photo-1530549387789-4c1017266635?q=80&w=2670&auto=format&fit=crop"),
            createMockMedia("https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?q=80&w=2670&auto=format&fit=crop"),
            createMockMedia("https://images.unsplash.com/photo-1571008887538-b36bb32f4571?q=80&w=2670&auto=format&fit=crop"),
        ],
    },
    {
        id: '6',
        titleEn: 'Abstract Thought',
        titleFr: ' Pensée Abstraite',
        slug: 'abstract-thought',
        descriptionEn: 'Lecture series on contemporary philosophy exploring questions about existence, meaning, and our place in the universe. Join renowned philosophers, writers, and thinkers for weekly discussions that challenge conventional wisdom and spark new perspectives. Each session delves into different philosophical traditions and modern interpretations, from existentialism to phenomenology and beyond. Engage in thought-provoking conversations that expand your understanding of yourself and the world around you.',
        descriptionFr: 'Série de conférences sur la philosophie contemporaine explorant des questions sur l\'existence, le sens et notre place dans l\'univers. Rejoignez des philosophes renommés, des écrivains et des penseurs pour des discussions hebdomadaires qui remettent en question la sagesse conventionnelle et suscitent de nouvelles perspectives. Chaque séance approfondit différentes traditions philosophiques et interprétations modernes, de l\'existentialisme à la phénoménologie et au-delà. Engagez-vous dans des conversations stimulantes qui élargissent votre compréhension de vous-même et du monde qui vous entoure.',
        subtitleEn: 'Philosophical dialogues on existence, meaning, and contemporary society',
        subtitleFr: 'Dialogues philosophiques sur l\'existence, le sens et la société contemporaine',
        startDate: new Date('2026-11-15T18:00:00Z'),
        endDate: new Date('2026-11-15T20:00:00Z'),
        locationEn: 'London',
        locationFr: 'Londres',
        venueNameEn: 'Royal Institution',
        venueNameFr: 'Institution Royale',
        streetAddressEn: '21 Albemarle St',
        streetAddressFr: '21 Albemarle St',
        districtEn: 'Mayfair',
        districtFr: 'Mayfair',
        cityEn: 'London',
        cityFr: 'Londres',
        postalCode: 'W1S 4BS',
        countryEn: 'UK',
        countryFr: 'Royaume-Uni',
        collaborators: JSON.stringify([
            { name: 'Prof. Alan Waters', role: 'Speaker' },
            { name: 'Philosophy Now', role: 'Media Partner' }
        ]),
        timings: JSON.stringify([
            { label: 'Lecture Series', time: '18:00 - 20:00 (Weekly)' }
        ]),
        curatorEn: 'Dr. Sophia Patel',
        curatorFr: 'Dr. Sophia Patel',
        materialsEn: 'Lecture Hall, Discussion Space',
        materialsFr: 'Salle de conférence, espace de discussion',
        admissionInfoEn: 'Free',
        admissionInfoFr: 'Gratuit',
        published: true,
        isSpotlight: false,
        categoryId: 'cat-2',
        category: MOCK_CATEGORIES[1],
        createdAt: new Date(),
        updatedAt: new Date(),
        coverMediaId: null,
        coverMedia: createMockMedia("https://images.unsplash.com/photo-1554907984-15263bfd63bd?q=80&w=2670&auto=format&fit=crop"),
        media: [
            createMockMedia("https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=2574&auto=format&fit=crop"),
            createMockMedia("https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=2670&auto=format&fit=crop"),
            createMockMedia("https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=2574&auto=format&fit=crop"),
            createMockMedia("https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=2670&auto=format&fit=crop"),
        ],
    },
    {
        id: '7',
        titleEn: 'Sustainable Living Workshop',
        titleFr: 'Atelier de Vie Durable',
        slug: 'sustainable-living-workshop',
        descriptionEn: 'Learn practical tips and techniques for sustainable living in this hands-on workshop. Explore eco-friendly practices, renewable energy solutions, and sustainable gardening. Expert instructors will guide you through composting, solar panel basics, water conservation, and creating a zero-waste home lifestyle. Connect with like-minded individuals and discover how small changes can make a big impact on our planet.',
        descriptionFr: 'Apprenez des conseils et techniques pratiques pour la vie durable dans cet atelier pratique. Explorez des pratiques écologiques, des solutions d\'énergie renouvelable et le jardinage durable. Des instructeurs experts vous guideront à travers le compostage, les bases des panneaux solaires, la conservation de l\'eau et la création d\'un mode de vie zéro déchet. Connectez-vous avec des personnes partageant les mêmes idées et découvrez comment petits changements peuvent avoir un grand impact sur notre planète.',
        subtitleEn: 'Practical eco-friendly solutions for everyday life',
        subtitleFr: 'Solutions écologiques pratiques pour la vie quotidienne',
        startDate: new Date('2026-12-05T10:00:00Z'),
        endDate: new Date('2026-12-05T16:00:00Z'),
        locationEn: 'Portland Community Center',
        locationFr: 'Centre Communautaire de Portland',
        venueNameEn: 'EcoCenter Portland',
        venueNameFr: 'ÉcoCentre Portland',
        streetAddressEn: '123 Green Way',
        streetAddressFr: '123 Green Way',
        districtEn: 'Pearl District',
        districtFr: 'Quartier Pearl',
        cityEn: 'Portland',
        cityFr: 'Portland',
        postalCode: '97209',
        countryEn: 'USA',
        countryFr: 'États-Unis',
        collaborators: JSON.stringify([
            { name: 'Green Earth Initiative', role: 'Organizer' },
            { name: 'City of Portland Sustainability Office', role: 'Partner' }
        ]),
        timings: JSON.stringify([
            { label: 'Registration', time: '09:30 - 10:00' },
            { label: 'Morning Sessions', time: '10:00 - 12:30' },
            { label: 'Lunch Break', time: '12:30 - 13:30' },
            { label: 'Afternoon Workshops', time: '13:30 - 16:00' }
        ]),
        curatorEn: 'Dr. Sarah Green',
        curatorFr: 'Dr. Sarah Green',
        materialsEn: 'Workshop Materials, Seeds, Compost Bin Demo',
        materialsFr: 'Matériels d\'atelier, graines, démo de bac à compost',
        admissionInfoEn: '$35 General Admission, Students Free with ID',
        admissionInfoFr: '35 $ entrée générale, gratuit pour les étudiants avec pièce d\'identité',
        published: true,
        isSpotlight: false,
        categoryId: 'cat-3',
        category: MOCK_CATEGORIES[2],
        createdAt: new Date(),
        updatedAt: new Date(),
        coverMediaId: null,
        coverMedia: createMockMedia("https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?q=80&w=2670&auto=format&fit=crop"),
        media: [
            createMockMedia("https://images.unsplash.com/photo-1416879595882-3373a0480b5b?q=80&w=2670&auto=format&fit=crop"),
            createMockMedia("https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?q=80&w=2670&auto=format&fit=crop"),
        ],
    },
];

export const MOCK_TALENTS = [
    {
        id: '1',
        firstName: 'Sarah',
        lastName: 'Johnson',
        roleEn: 'Lead Vocalist & Songwriter',
        roleFr: 'Chanteuse Principale & Autrice-Compositrice',
        bioEn: 'Award-winning vocalist with 10+ years of experience in jazz and soul music. Has performed at major festivals worldwide and released three critically acclaimed albums.',
        bioFr: 'Chanteuse primée avec plus de 10 ans d\'expérience dans le jazz et la musique soul. S\'est produite dans des festivals majeurs dans le monde entier et a sorti trois albums acclamés par la critique.',
        city: 'Nashville',
        country: 'USA',
        quoteEn: 'Music is the language of the soul, transcending all boundaries.',
        quoteFr: 'La musique est le langage de l\'âme, transcendant toutes les frontières.',
        specializationsEn: JSON.stringify([
            'Vocal Performance',
            'Songwriting',
            'Music Production'
        ]),
        specializationsFr: JSON.stringify([
            'Performance Vocale',
            'Écriture de Chansons',
            'Production Musicale'
        ]),
        socialLinks: JSON.stringify({
            instagram: 'https://instagram.com/sarahjohnson',
            twitter: 'https://twitter.com/sarahjohnson',
            website: 'https://sarah.johnson.com',
            email: 'sarah.johnson@email.com',
        }),
        published: true,
        categoryId: 'talent-cat-4',
        category: MOCK_TALENT_CATEGORIES[3],
        createdAt: new Date(),
        updatedAt: new Date(),
        profileMediaId: 'mock-profile-1',
        profileMedia: createMockMedia("https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=2564&auto=format&fit=crop"),
        media: [],
    },
    {
        id: '2',
        firstName: 'Michael',
        lastName: 'Chen',
        roleEn: 'Tech Entrepreneur & Speaker',
        roleFr: 'Entrepreneur Technologique & Conférencier',
        bioEn: 'Serial entrepreneur and technology innovator. Founded multiple successful startups in the AI and fintech space. Regular speaker at major tech conferences.',
        bioFr: 'Entrepreneur en série et innovateur technologique. A fondé plusieurs startups à succès dans l\'IA et la fintech. Conférencier régulier dans les grandes conférences technologiques.',
        city: 'San Francisco',
        country: 'USA',
        quoteEn: 'Innovation happens at the intersection of technology and humanity.',
        quoteFr: 'L\'innovation se produit à l\'intersection de la technologie et de l\'humanité.',
        specializationsEn: JSON.stringify([
            'Artificial Intelligence',
            'Product Strategy',
            'Public Speaking'
        ]),
        specializationsFr: JSON.stringify([
            'Intelligence Artificielle',
            'Stratégie Produit',
            'Prise de Parole en Public'
        ]),
        socialLinks: JSON.stringify({
            linkedin: 'https://linkedin.com/in/michaelchen',
            twitter: 'https://twitter.com/michaelchen',
        }),
        published: true,
        categoryId: 'talent-cat-2',
        category: MOCK_TALENT_CATEGORIES[1],
        createdAt: new Date(),
        updatedAt: new Date(),
        profileMediaId: null,
        profileMedia: createMockMedia("https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=2574&auto=format&fit=crop"),
        media: [],
    },
    {
        id: '3',
        firstName: 'Emma',
        lastName: 'Rodriguez',
        roleEn: 'Contemporary Artist',
        roleFr: 'Artiste Contemporaine',
        bioEn: 'Contemporary visual artist specializing in mixed media and installations. Her work has been featured in galleries across Europe and North America.',
        bioFr: 'Artiste visuelle contemporaine spécialisée dans les médias mixtes et les installations. Ses œuvres ont été présentées dans des galeries à travers l\'Europe et l\'Amérique du Nord.',
        city: 'Barcelona',
        country: 'Spain',
        quoteEn: 'Art is not what you see, but what you make others see.',
        quoteFr: 'L\'art n\'est pas ce que vous voyez, mais ce que vous faites voir aux autres.',
        specializationsEn: JSON.stringify([
            'Mixed Media',
            'Installation Art',
            'Digital Sculpture'
        ]),
        specializationsFr: JSON.stringify([
            'Médias Mixtes',
            'Art d\'Installation',
            'Sculpture Numérique'
        ]),
        socialLinks: JSON.stringify({
            instagram: 'https://instagram.com/emmarodriguez',
            website: 'https://emmarodriguez.art',
        }),
        published: true,
        categoryId: 'talent-cat-1',
        category: MOCK_TALENT_CATEGORIES[0],
        createdAt: new Date(),
        updatedAt: new Date(),
        profileMediaId: null,
        profileMedia: createMockMedia("https://images.unsplash.com/photo-1531123897727-8f129e1688ce?q=80&w=2574&auto=format&fit=crop"),
        media: [],
    },
    {
        id: '4',
        firstName: 'David',
        lastName: 'Thompson',
        roleEn: 'Celebrity Chef',
        roleFr: 'Chef Célèbre',
        bioEn: 'Michelin-starred chef and culinary innovator. Known for his farm-to-table approach and sustainable cooking practices. Author of three bestselling cookbooks.',
        bioFr: 'Chef étoilé Michelin et innovateur culinaire. Connu pour son approche de la ferme à la table et ses pratiques de cuisine durable. Auteur de trois livres de cuisine bestsellers.',
        city: 'London',
        country: 'UK',
        quoteEn: 'Cooking is about creating experiences, not just meals.',
        quoteFr: 'La cuisine consiste à créer des expériences, pas seulement des repas.',
        specializationsEn: JSON.stringify([
            'French Cuisine',
            'Pastry Arts',
            'Restaurant Management'
        ]),
        specializationsFr: JSON.stringify([
            'Cuisine Française',
            'Arts de la Pâtisserie',
            'Gestion de Restaurant'
        ]),
        socialLinks: JSON.stringify({
            instagram: 'https://instagram.com/chefthompson',
            website: 'https://davidthompson.com',
        }),
        published: true,
        categoryId: 'talent-cat-3',
        category: MOCK_TALENT_CATEGORIES[2],
        createdAt: new Date(),
        updatedAt: new Date(),
        profileMediaId: null,
        profileMedia: null as typeof createMockMedia extends () => infer R ? R : never,
        media: [],
    },
    {
        id: '5',
        firstName: 'Lisa',
        lastName: 'Martinez',
        roleEn: 'Professional Marathon Runner',
        roleFr: 'Coureuse Professionnelle de Marathon',
        bioEn: 'Olympic athlete and marathon champion. Holds multiple national records and actively promotes youth sports programs and fitness education.',
        bioFr: 'Athlète olympique et championne de marathon. Détient plusieurs records nationaux et promeut activement les programmes sportifs pour jeunes et l\'éducation physique.',
        city: 'Nairobi',
        country: 'Kenya',
        quoteEn: 'Every mile is a meditation, every race is a journey.',
        quoteFr: 'Chaque kilomètre est une méditation, chaque course est un voyage.',
        specializationsEn: JSON.stringify([
            'Long Distance Running',
            'Sports Nutrition',
            'Athletic Coaching'
        ]),
        specializationsFr: JSON.stringify([
            'Course de Longue Distance',
            'Nutrition Sportive',
            'Entraînement Athlétique'
        ]),
        socialLinks: JSON.stringify({
            instagram: 'https://instagram.com/lisamartinez',
            twitter: 'https://twitter.com/lisamartinez',
        }),
        published: true,
        categoryId: 'talent-cat-5',
        category: MOCK_TALENT_CATEGORIES[4],
        createdAt: new Date(),
        updatedAt: new Date(),
        profileMediaId: null,
        profileMedia: null as typeof createMockMedia extends () => infer R ? R : never,
        media: [],
    },
];

export const MOCK_SESSIONS = [
    {
        id: '550e8400-e29b-41d4-a716-446655440001',
        eventId: '1',
        title: 'General Admission',
        titleEn: 'General Admission',
        titleFr: 'Entrée générale',
        description: 'Standard entry to the Summer Music Festival',
        descriptionEn: 'Standard entry to the Summer Music Festival',
        descriptionFr: 'Entrée standard au Summer Music Festival',
        startTime: new Date('2026-07-15T18:00:00Z'),
        endTime: new Date('2026-07-15T23:00:00Z'),
        totalCapacity: 5000,
        availableCapacity: 4997,
        priceAmount: 4500,
        currency: 'USD',
        published: true,
        allowWaitlist: true,
        badgeType: 'none' as const,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: '660e8400-e29b-41d4-a716-446655440002',
        eventId: '1',
        title: 'VIP Access',
        titleEn: 'VIP Access',
        titleFr: 'Accès VIP',
        descriptionEn: 'Premium experience with backstage access and exclusive amenities',
        descriptionFr: 'Expérience premium avec accès backstage et équipements exclusifs',
        startTime: new Date('2026-07-15T18:00:00Z'),
        endTime: new Date('2026-07-15T23:00:00Z'),
        totalCapacity: 500,
        availableCapacity: 498,
        priceAmount: 9000,
        currency: 'USD',
        published: true,
        allowWaitlist: true,
        badgeType: 'vip' as const,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: '770e8400-e29b-41d4-a716-446655440003',
        eventId: '1',
        title: 'Early Bird Special',
        titleEn: 'Early Bird Special',
        titleFr: 'Tarif early bird',
        descriptionEn: 'Discounted rate for early bookers - limited time offer',
        descriptionFr: 'Tarif réduit pour les early adopters - offre à durée limitée',
        startTime: new Date('2026-07-15T18:00:00Z'),
        endTime: new Date('2026-07-15T23:00:00Z'),
        totalCapacity: 1000,
        availableCapacity: 856,
        priceAmount: 3500,
        currency: 'USD',
        published: true,
        allowWaitlist: true,
        badgeType: 'limited' as const,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: '880e8400-e29b-41d4-a716-446655440004',
        eventId: '1',
        title: 'Student Discount',
        titleEn: 'Student Discount',
        titleFr: 'Tarif étudiant',
        descriptionEn: 'Special pricing for students with valid ID',
        descriptionFr: 'Tarif spécial pour les étudiants avec pièce d\'identité valide',
        startTime: new Date('2026-07-15T18:00:00Z'),
        endTime: new Date('2026-07-15T23:00:00Z'),
        totalCapacity: 500,
        availableCapacity: 423,
        priceAmount: 3000,
        currency: 'USD',
        published: true,
        allowWaitlist: false,
        badgeType: 'none' as const,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: '990e8400-e29b-41d4-a716-446655440005',
        eventId: '1',
        title: 'Two-Day Festival Pass',
        titleEn: 'Two-Day Festival Pass',
        titleFr: 'Pass festival 2 jours',
        descriptionEn: 'Access to both festival days with exclusive merchandise',
        descriptionFr: 'Accès aux deux jours du festival avec marchandises exclusives',
        startTime: new Date('2026-07-15T18:00:00Z'),
        endTime: new Date('2026-07-16T23:00:00Z'),
        totalCapacity: 2000,
        availableCapacity: 1876,
        priceAmount: 7500,
        currency: 'USD',
        published: true,
        allowWaitlist: true,
        badgeType: 'best_value' as const,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 'aa0e8400-e29b-41d4-a716-446655440006',
        eventId: '1',
        title: 'Group Package (5+)',
        titleEn: 'Group Package (5+)',
        titleFr: 'Forfait groupe (5+)',
        descriptionEn: 'Special group rate for parties of 5 or more',
        descriptionFr: 'Tarif de groupe spécial pour les groupes de 5 personnes ou plus',
        startTime: new Date('2026-07-15T18:00:00Z'),
        endTime: new Date('2026-07-15T23:00:00Z'),
        totalCapacity: 1500,
        availableCapacity: 1324,
        priceAmount: 3800,
        currency: 'USD',
        published: true,
        allowWaitlist: true,
        badgeType: 'popular' as const,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 'bb0e8400-e29b-41d4-a716-446655440007',
        eventId: '1',
        title: 'Premium Backstage Experience',
        titleEn: 'Premium Backstage Experience',
        titleFr: 'Expérience backstage premium',
        descriptionEn: 'All-access backstage pass with meet & greet opportunities',
        descriptionFr: 'Pass backstage tout accès avec opportunités de meet & greet',
        startTime: new Date('2026-07-15T18:00:00Z'),
        endTime: new Date('2026-07-15T23:00:00Z'),
        totalCapacity: 50,
        availableCapacity: 42,
        priceAmount: 15000,
        currency: 'USD',
        published: true,
        allowWaitlist: false,
        badgeType: 'featured' as const,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 'cc0e8400-e29b-41d4-a716-446655440008',
        eventId: '1',
        title: 'Family Package',
        titleEn: 'Family Package',
        titleFr: 'Forfait famille',
        descriptionEn: 'Discounted rate for families (2 adults + 2 children under 12)',
        descriptionFr: 'Tarif réduit pour les familles (2 adultes + 2 enfants de moins de 12 ans)',
        startTime: new Date('2026-07-15T18:00:00Z'),
        endTime: new Date('2026-07-15T23:00:00Z'),
        totalCapacity: 300,
        availableCapacity: 267,
        priceAmount: 12000,
        currency: 'USD',
        published: true,
        allowWaitlist: true,
        badgeType: 'none' as const,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 'dd0e8400-e29b-41d4-a716-446655440009',
        eventId: '2',
        title: 'Professional Pass',
        titleEn: 'Professional Pass',
        titleFr: 'Pass professionnel',
        descriptionEn: 'Full access to all keynotes, sessions, and networking events',
        descriptionFr: 'Accès complet à toutes les conférences, sessions et événements de réseautage',
        startTime: new Date('2026-09-20T09:00:00Z'),
        endTime: new Date('2026-09-22T17:00:00Z'),
        totalCapacity: 1000,
        availableCapacity: 999,
        priceAmount: 29900,
        currency: 'USD',
        published: true,
        allowWaitlist: true,
        badgeType: 'featured' as const,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 'ee0e8400-e29b-41d4-a716-446655440010',
        eventId: '2',
        title: 'All Access Pass',
        titleEn: 'All Access Pass',
        titleFr: 'Pass tout accès',
        descriptionEn: 'Ultimate experience with VIP sessions, private meetings, and exclusive workshops',
        descriptionFr: 'Expérience ultime avec sessions VIP, réunions privées et ateliers exclusifs',
        startTime: new Date('2026-09-20T09:00:00Z'),
        endTime: new Date('2026-09-22T17:00:00Z'),
        totalCapacity: 100,
        availableCapacity: 97,
        priceAmount: 89900,
        currency: 'USD',
        published: true,
        allowWaitlist: false,
        badgeType: 'vip' as const,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 'ff0e8400-e29b-41d4-a716-446655440011',
        eventId: '3',
        title: 'Full Day Pass',
        titleEn: 'Full Day Pass',
        titleFr: 'Pass journée complète',
        descriptionEn: 'Experience all culinary delights and wine tastings throughout the day',
        descriptionFr: 'Profitez de toutes les délices culinaires et dégustations de vin tout au long de la journée',
        startTime: new Date('2026-08-05T12:00:00Z'),
        endTime: new Date('2026-08-07T20:00:00Z'),
        totalCapacity: 500,
        availableCapacity: 491,
        priceAmount: 8500,
        currency: 'USD',
        published: true,
        allowWaitlist: true,
        badgeType: 'none' as const,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: '001e8400-e29b-41d4-a716-446655440012',
        eventId: '5',
        title: 'General Admission',
        titleEn: 'General Admission',
        titleFr: 'Entrée générale',
        descriptionEn: 'Access to the contemporary art and design exhibition',
        descriptionFr: 'Accès à l\'exposition d\'art et de design contemporain',
        startTime: new Date('2026-10-10T10:00:00Z'),
        endTime: new Date('2026-10-31T18:00:00Z'),
        totalCapacity: 1000,
        availableCapacity: 997,
        priceAmount: 8500,
        currency: 'USD',
        published: true,
        allowWaitlist: true,
        badgeType: 'none' as const,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: '112e8400-e29b-41d4-a716-446655440013',
        eventId: '6',
        title: 'Registration',
        titleEn: 'Registration',
        titleFr: 'Inscription',
        descriptionEn: 'Official registration for the charity marathon',
        descriptionFr: 'Inscription officielle au marathon caritatif',
        startTime: new Date('2026-11-15T06:00:00Z'),
        endTime: new Date('2026-11-15T14:00:00Z'),
        totalCapacity: 10000,
        availableCapacity: 9999,
        priceAmount: 5000,
        currency: 'USD',
        published: true,
        allowWaitlist: true,
        badgeType: 'none' as const,
        createdAt: new Date(),
        updatedAt: new Date()
    }
];

export const MOCK_RESERVATIONS = [
    {
        id: 'res-1',
        eventSessionId: '550e8400-e29b-41d4-a716-446655440001',
        guestName: 'Alice Williams',
        guestEmail: 'alice.williams@example.com',
        guestPhone: '+1234567890',
        quantity: 2,
        totalAmount: 9000,
        currency: 'USD',
        status: 'confirmed',
        accessToken: 'acc_abc123def456',
        ipAddress: '192.168.1.1',
        userAgent: 'Mozilla/5.0...',
        expiresAt: new Date(Date.now() + 13 * 24 * 60 * 60 * 1000).toISOString(),
        confirmedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
        cancelledAt: null,
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
        paymentStatus: 'succeeded'
    },
    {
        id: 'res-2',
        eventSessionId: 'dd0e8400-e29b-41d4-a716-446655440009',
        guestName: 'Bob Martinez',
        guestEmail: 'bob.martinez@example.com',
        guestPhone: '+1234567891',
        quantity: 1,
        totalAmount: 29900,
        currency: 'USD',
        status: 'confirmed',
        accessToken: 'acc_def789ghi012',
        ipAddress: '192.168.1.2',
        userAgent: 'Mozilla/5.0...',
        expiresAt: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
        confirmedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
        cancelledAt: null,
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
        paymentStatus: 'succeeded'
    },
    {
        id: 'res-3',
        eventSessionId: 'ff0e8400-e29b-41d4-a716-446655440011',
        guestName: 'Charlotte Chen',
        guestEmail: 'charlotte.chen@example.com',
        guestPhone: '+1234567892',
        quantity: 4,
        totalAmount: 34000,
        currency: 'USD',
        status: 'confirmed',
        accessToken: 'acc_ghi345jkl678',
        ipAddress: '192.168.1.3',
        userAgent: 'Mozilla/5.0...',
        expiresAt: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
        confirmedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
        cancelledAt: null,
        createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
        paymentStatus: 'succeeded'
    },
    {
        id: 'res-4',
        eventSessionId: '550e8400-e29b-41d4-a716-446655440001',
        guestName: 'David Thompson',
        guestEmail: 'david.thompson@example.com',
        guestPhone: '+1234567893',
        quantity: 1,
        totalAmount: 4500,
        currency: 'USD',
        status: 'pending',
        accessToken: 'acc_jkl901mno234',
        ipAddress: '192.168.1.4',
        userAgent: 'Mozilla/5.0...',
        expiresAt: new Date(Date.now() + 14 * 60 * 1000).toISOString(),
        confirmedAt: null,
        cancelledAt: null,
        createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        paymentStatus: 'pending'
    },
    {
        id: 'res-5',
        eventSessionId: '660e8400-e29b-41d4-a716-446655440002',
        guestName: 'Emma Rodriguez',
        guestEmail: 'emma.rodriguez@example.com',
        guestPhone: '+1234567894',
        quantity: 2,
        totalAmount: 18000,
        currency: 'USD',
        status: 'confirmed',
        accessToken: 'acc_mno567pqr890',
        ipAddress: '192.168.1.5',
        userAgent: 'Mozilla/5.0...',
        expiresAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 13 * 60 * 1000).toISOString(),
        confirmedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
        cancelledAt: null,
        createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
        paymentStatus: 'succeeded'
    },
    {
        id: 'res-6',
        eventSessionId: '001e8400-e29b-41d4-a716-446655440012',
        guestName: 'Frank Miller',
        guestEmail: 'frank.miller@example.com',
        guestPhone: '+1234567895',
        quantity: 3,
        totalAmount: 25500,
        currency: 'USD',
        status: 'cancelled',
        accessToken: 'acc_pqr123stu456',
        ipAddress: '192.168.1.6',
        userAgent: 'Mozilla/5.0...',
        expiresAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
        confirmedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000 + 12 * 60 * 1000).toISOString(),
        cancelledAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        paymentStatus: 'refunded'
    },
    {
        id: 'res-7',
        eventSessionId: '112e8400-e29b-41d4-a716-446655440013',
        guestName: 'Grace Kim',
        guestEmail: 'grace.kim@example.com',
        guestPhone: '+1234567896',
        quantity: 1,
        totalAmount: 50,
        currency: 'USD',
        status: 'confirmed',
        accessToken: 'acc_stu789vwx012',
        ipAddress: '192.168.1.7',
        userAgent: 'Mozilla/5.0...',
        expiresAt: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
        confirmedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 8 * 60 * 1000).toISOString(),
        cancelledAt: null,
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 8 * 60 * 1000).toISOString(),
        paymentStatus: 'succeeded'
    },
    {
        id: 'res-8',
        eventSessionId: 'ee0e8400-e29b-41d4-a716-446655440010',
        guestName: 'Henry Zhang',
        guestEmail: 'henry.zhang@example.com',
        guestPhone: '+1234567897',
        quantity: 2,
        totalAmount: 179800,
        currency: 'USD',
        status: 'confirmed',
        accessToken: 'acc_vwx345yzd678',
        ipAddress: '192.168.1.8',
        userAgent: 'Mozilla/5.0...',
        expiresAt: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
        confirmedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 18 * 60 * 1000).toISOString(),
        cancelledAt: null,
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 18 * 60 * 1000).toISOString(),
        paymentStatus: 'succeeded'
    },
    {
        id: 'res-9',
        eventSessionId: 'ee0e8400-e29b-41d4-a716-446655440010',
        guestName: 'Isabella Lopez',
        guestEmail: 'isabella.lopez@example.com',
        guestPhone: '+1234567898',
        quantity: 1,
        totalAmount: 89900,
        currency: 'USD',
        status: 'pending',
        accessToken: 'acc_yzd901abe234',
        ipAddress: '192.168.1.9',
        userAgent: 'Mozilla/5.0...',
        expiresAt: new Date(Date.now() + 14 * 60 * 1000).toISOString(),
        confirmedAt: null,
        cancelledAt: null,
        createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
        paymentStatus: 'pending'
    },
    {
        id: 'res-10',
        eventSessionId: 'ff0e8400-e29b-41d4-a716-446655440011',
        guestName: 'James Wilson',
        guestEmail: 'james.wilson@example.com',
        guestPhone: '+1234567899',
        quantity: 5,
        totalAmount: 42500,
        currency: 'USD',
        status: 'confirmed',
        accessToken: 'acc_bef567cgh890',
        ipAddress: '192.168.1.10',
        userAgent: 'Mozilla/5.0...',
        expiresAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
        confirmedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000 + 25 * 60 * 1000).toISOString(),
        cancelledAt: null,
        createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000 + 25 * 60 * 1000).toISOString(),
        paymentStatus: 'succeeded'
    },
    {
        id: 'res-11',
        eventSessionId: '770e8400-e29b-41d4-a716-446655440003',
        guestName: 'Sophie Martin',
        guestEmail: 'sophie.martin@example.com',
        guestPhone: '+33612345678',
        quantity: 2,
        totalAmount: 7000,
        currency: 'USD',
        status: 'confirmed',
        accessToken: 'acc_early123bird456',
        ipAddress: '192.168.1.11',
        userAgent: 'Mozilla/5.0...',
        expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
        confirmedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
        cancelledAt: null,
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
        paymentStatus: 'succeeded'
    },
    {
        id: 'res-12',
        eventSessionId: '880e8400-e29b-41d4-a716-446655440004',
        guestName: 'Lucas Dubois',
        guestEmail: 'lucas.dubois@example.com',
        guestPhone: '+33698765432',
        quantity: 1,
        totalAmount: 3000,
        currency: 'USD',
        status: 'confirmed',
        accessToken: 'acc_student789uni123',
        ipAddress: '192.168.1.12',
        userAgent: 'Mozilla/5.0...',
        expiresAt: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
        confirmedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
        cancelledAt: null,
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
        paymentStatus: 'succeeded'
    },
    {
        id: 'res-13',
        eventSessionId: '990e8400-e29b-41d4-a716-446655440005',
        guestName: 'Marie Leclerc',
        guestEmail: 'marie.leclerc@example.com',
        guestPhone: '+33611223344',
        quantity: 3,
        totalAmount: 22500,
        currency: 'USD',
        status: 'confirmed',
        accessToken: 'acc_twoday456pass789',
        ipAddress: '192.168.1.13',
        userAgent: 'Mozilla/5.0...',
        expiresAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
        confirmedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
        cancelledAt: null,
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
        paymentStatus: 'succeeded'
    },
    {
        id: 'res-14',
        eventSessionId: 'aa0e8400-e29b-41d4-a716-446655440006',
        guestName: 'Pierre Bernard',
        guestEmail: 'pierre.bernard@example.com',
        guestPhone: '+33655667788',
        quantity: 6,
        totalAmount: 22800,
        currency: 'USD',
        status: 'confirmed',
        accessToken: 'acc_group678party123',
        ipAddress: '192.168.1.14',
        userAgent: 'Mozilla/5.0...',
        expiresAt: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
        confirmedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
        cancelledAt: null,
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
        paymentStatus: 'succeeded'
    },
    {
        id: 'res-15',
        eventSessionId: 'bb0e8400-e29b-41d4-a716-446655440007',
        guestName: 'Claire Fontaine',
        guestEmail: 'claire.fontaine@example.com',
        guestPhone: '+33699887766',
        quantity: 2,
        totalAmount: 30000,
        currency: 'USD',
        status: 'confirmed',
        accessToken: 'acc_vip987backstage456',
        ipAddress: '192.168.1.15',
        userAgent: 'Mozilla/5.0...',
        expiresAt: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
        confirmedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 25 * 60 * 1000).toISOString(),
        cancelledAt: null,
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 25 * 60 * 1000).toISOString(),
        paymentStatus: 'succeeded'
    },
    {
        id: 'res-16',
        eventSessionId: 'cc0e8400-e29b-41d4-a716-446655440008',
        guestName: 'Thomas Roux',
        guestEmail: 'thomas.roux@example.com',
        guestPhone: '+33644556677',
        quantity: 1,
        totalAmount: 12000,
        currency: 'USD',
        status: 'confirmed',
        accessToken: 'acc_family321pack789',
        ipAddress: '192.168.1.16',
        userAgent: 'Mozilla/5.0...',
        expiresAt: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000).toISOString(),
        confirmedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 12 * 60 * 1000).toISOString(),
        cancelledAt: null,
        createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 12 * 60 * 1000).toISOString(),
        paymentStatus: 'succeeded'
    }
];

export const MOCK_PAYMENTS = [
    {
        id: 'pay-1',
        reservationId: 'res-1',
        stripePaymentIntentId: 'pi_1abc2def3ghi4jkl',
        stripeClientSecret: 'pi_1abc2def3ghi4jkl_secret_xyz',
        amount: 9000,
        currency: 'USD',
        status: 'succeeded',
        stripeCustomerId: 'cus_abc123',
        stripePaymentMethodId: 'pm_def456',
        refundedAmount: 0,
        receiptUrl: 'https://stripe.com/receipts/rpt_abc123',
        stripeChargeId: 'ch_ghi789',
        lastError: null,
        idempotencyKey: 'idem_abc123',
        webhookProcessedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString()
    },
    {
        id: 'pay-2',
        reservationId: 'res-2',
        stripePaymentIntentId: 'pi_2mno3pqr4stu5vwx',
        stripeClientSecret: 'pi_2mno3pqr4stu5vwx_secret_yza',
        amount: 29900,
        currency: 'USD',
        status: 'succeeded',
        stripeCustomerId: 'cus_bcd234',
        stripePaymentMethodId: 'pm_efg567',
        refundedAmount: 0,
        receiptUrl: 'https://stripe.com/receipts/rpt_bcd234',
        stripeChargeId: 'ch_jkl012',
        lastError: null,
        idempotencyKey: 'idem_bcd234',
        webhookProcessedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString()
    },
    {
        id: 'pay-3',
        reservationId: 'res-3',
        stripePaymentIntentId: 'pi_3bcd4efg5hij6klm',
        stripeClientSecret: 'pi_3bcd4efg5hij6klm_secret_nop',
        amount: 34000,
        currency: 'USD',
        status: 'succeeded',
        stripeCustomerId: 'cus_cde345',
        stripePaymentMethodId: 'pm_hij678',
        refundedAmount: 0,
        receiptUrl: 'https://stripe.com/receipts/rpt_cde345',
        stripeChargeId: 'ch_mno345',
        lastError: null,
        idempotencyKey: 'idem_cde345',
        webhookProcessedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
        createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString()
    },
    {
        id: 'pay-4',
        reservationId: 'res-4',
        stripePaymentIntentId: 'pi_4opq5rst6uvw7xyz',
        stripeClientSecret: 'pi_4opq5rst6uvw7xyz_secret_bcd',
        amount: 4500,
        currency: 'USD',
        status: 'pending',
        stripeCustomerId: null,
        stripePaymentMethodId: null,
        refundedAmount: 0,
        receiptUrl: null,
        stripeChargeId: null,
        lastError: null,
        idempotencyKey: 'idem_pending1',
        webhookProcessedAt: null,
        createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString()
    },
    {
        id: 'pay-5',
        reservationId: 'res-5',
        stripePaymentIntentId: 'pi_5cde6fgh7ijk8lmn',
        stripeClientSecret: 'pi_5cde6fgh7ijk8lmn_secret_efg',
        amount: 18000,
        currency: 'USD',
        status: 'succeeded',
        stripeCustomerId: 'cus_def456',
        stripePaymentMethodId: 'pm_pqr789',
        refundedAmount: 0,
        receiptUrl: 'https://stripe.com/receipts/rpt_def456',
        stripeChargeId: 'ch_rst456',
        lastError: null,
        idempotencyKey: 'idem_def456',
        webhookProcessedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
        createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString()
    },
    {
        id: 'pay-6',
        reservationId: 'res-6',
        stripePaymentIntentId: 'pi_6ghi7jkl8mno9pqr',
        stripeClientSecret: 'pi_6ghi7jkl8mno9pqr_secret_hij',
        amount: 25500,
        currency: 'USD',
        status: 'refunded',
        stripeCustomerId: 'cus_efg567',
        stripePaymentMethodId: 'pm_stu890',
        refundedAmount: 25500,
        receiptUrl: 'https://stripe.com/receipts/rpt_efg567',
        stripeChargeId: 'ch_uvw789',
        lastError: null,
        idempotencyKey: 'idem_efg567',
        webhookProcessedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
        id: 'pay-7',
        reservationId: 'res-7',
        stripePaymentIntentId: 'pi_7jkl8mno9pqr0stu',
        stripeClientSecret: 'pi_7jkl8mno9pqr0stu_secret_jkl',
        amount: 5000,
        currency: 'USD',
        status: 'succeeded',
        stripeCustomerId: 'cus_fgh678',
        stripePaymentMethodId: 'pm_vwx012',
        refundedAmount: 0,
        receiptUrl: 'https://stripe.com/receipts/rpt_fgh678',
        stripeChargeId: 'ch_xyz890',
        lastError: null,
        idempotencyKey: 'idem_fgh678',
        webhookProcessedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 8 * 60 * 1000).toISOString(),
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 8 * 60 * 1000).toISOString()
    },
    {
        id: 'pay-8',
        reservationId: 'res-8',
        stripePaymentIntentId: 'pi_8mno9pqr0stu1vwx',
        stripeClientSecret: 'pi_8mno9pqr0stu1vwx_secret_mno',
        amount: 179800,
        currency: 'USD',
        status: 'succeeded',
        stripeCustomerId: 'cus_ghi789',
        stripePaymentMethodId: 'pm_yza123',
        refundedAmount: 0,
        receiptUrl: 'https://stripe.com/receipts/rpt_ghi789',
        stripeChargeId: 'ch_abcd12',
        lastError: null,
        idempotencyKey: 'idem_ghi789',
        webhookProcessedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 18 * 60 * 1000).toISOString(),
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 18 * 60 * 1000).toISOString()
    },
    {
        id: 'pay-9',
        reservationId: 'res-9',
        stripePaymentIntentId: 'pi_9opq0rst1uvw2xyz',
        stripeClientSecret: 'pi_9opq0rst1uvw2xyz_secret_opq',
        amount: 89900,
        currency: 'USD',
        status: 'processing',
        stripeCustomerId: 'cus_hij890',
        stripePaymentMethodId: 'pm_bcd234',
        refundedAmount: 0,
        receiptUrl: null,
        stripeChargeId: null,
        lastError: null,
        idempotencyKey: 'idem_hij890',
        webhookProcessedAt: null,
        createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString()
    },
    {
        id: 'pay-10',
        reservationId: 'res-10',
        stripePaymentIntentId: 'pi_0pqr1stu2vwx3yz',
        stripeClientSecret: 'pi_0pqr1stu2vwx3yz_secret_pqr',
        amount: 42500,
        currency: 'USD',
        status: 'succeeded',
        stripeCustomerId: 'cus_ijk901',
        stripePaymentMethodId: 'pm_efg345',
        refundedAmount: 0,
        receiptUrl: 'https://stripe.com/receipts/rpt_ijk901',
        stripeChargeId: 'ch_ghij34',
        lastError: null,
        idempotencyKey: 'idem_ijk901',
        webhookProcessedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000 + 25 * 60 * 1000).toISOString(),
        createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000 + 25 * 60 * 1000).toISOString()
    },
    // Add some failed payments for analytics
    {
        id: 'pay-11',
        reservationId: null,
        stripePaymentIntentId: 'pi_1failed2payment3',
        stripeClientSecret: 'pi_1failed2payment3_secret_fail',
        amount: 15000,
        currency: 'USD',
        status: 'failed',
        stripeCustomerId: null,
        stripePaymentMethodId: 'pm_failed1',
        refundedAmount: 0,
        receiptUrl: null,
        stripeChargeId: null,
        lastError: 'Card declined - insufficient funds',
        idempotencyKey: 'idem_failed1',
        webhookProcessedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
        id: 'pay-12',
        reservationId: null,
        stripePaymentIntentId: 'pi_2another3failed4',
        stripeClientSecret: 'pi_2another3failed4_secret_fail2',
        amount: 7500,
        currency: 'USD',
        status: 'failed',
        stripeCustomerId: null,
        stripePaymentMethodId: 'pm_failed2',
        refundedAmount: 0,
        receiptUrl: null,
        stripeChargeId: null,
        lastError: 'Payment method authentication failed',
        idempotencyKey: 'idem_failed2',
        webhookProcessedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString()
    },
    {
        id: 'pay-13',
        reservationId: 'res-11',
        stripePaymentIntentId: 'pi_musicfest2026_001',
        stripeClientSecret: 'pi_musicfest2026_001_secret_abc',
        amount: 7000,
        currency: 'USD',
        status: 'succeeded',
        stripeCustomerId: 'cus_music_001',
        stripePaymentMethodId: 'pm_music_001',
        refundedAmount: 0,
        receiptUrl: 'https://stripe.com/receipts/rpt_music_001',
        stripeChargeId: 'ch_music_001',
        lastError: null,
        idempotencyKey: 'idem_music_001',
        webhookProcessedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString()
    },
    {
        id: 'pay-14',
        reservationId: 'res-12',
        stripePaymentIntentId: 'pi_musicfest2026_002',
        stripeClientSecret: 'pi_musicfest2026_002_secret_def',
        amount: 3000,
        currency: 'USD',
        status: 'succeeded',
        stripeCustomerId: 'cus_music_002',
        stripePaymentMethodId: 'pm_music_002',
        refundedAmount: 0,
        receiptUrl: 'https://stripe.com/receipts/rpt_music_002',
        stripeChargeId: 'ch_music_002',
        lastError: null,
        idempotencyKey: 'idem_music_002',
        webhookProcessedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString()
    },
    {
        id: 'pay-15',
        reservationId: 'res-13',
        stripePaymentIntentId: 'pi_musicfest2026_003',
        stripeClientSecret: 'pi_musicfest2026_003_secret_ghi',
        amount: 22500,
        currency: 'USD',
        status: 'succeeded',
        stripeCustomerId: 'cus_music_003',
        stripePaymentMethodId: 'pm_music_003',
        refundedAmount: 0,
        receiptUrl: 'https://stripe.com/receipts/rpt_music_003',
        stripeChargeId: 'ch_music_003',
        lastError: null,
        idempotencyKey: 'idem_music_003',
        webhookProcessedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString()
    },
    {
        id: 'pay-16',
        reservationId: 'res-14',
        stripePaymentIntentId: 'pi_musicfest2026_004',
        stripeClientSecret: 'pi_musicfest2026_004_secret_jkl',
        amount: 22800,
        currency: 'USD',
        status: 'succeeded',
        stripeCustomerId: 'cus_music_004',
        stripePaymentMethodId: 'pm_music_004',
        refundedAmount: 0,
        receiptUrl: 'https://stripe.com/receipts/rpt_music_004',
        stripeChargeId: 'ch_music_004',
        lastError: null,
        idempotencyKey: 'idem_music_004',
        webhookProcessedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString()
    },
    {
        id: 'pay-17',
        reservationId: 'res-15',
        stripePaymentIntentId: 'pi_musicfest2026_005',
        stripeClientSecret: 'pi_musicfest2026_005_secret_mno',
        amount: 30000,
        currency: 'USD',
        status: 'succeeded',
        stripeCustomerId: 'cus_music_005',
        stripePaymentMethodId: 'pm_music_005',
        refundedAmount: 0,
        receiptUrl: 'https://stripe.com/receipts/rpt_music_005',
        stripeChargeId: 'ch_music_005',
        lastError: null,
        idempotencyKey: 'idem_music_005',
        webhookProcessedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 25 * 60 * 1000).toISOString(),
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 25 * 60 * 1000).toISOString()
    },
    {
        id: 'pay-18',
        reservationId: 'res-16',
        stripePaymentIntentId: 'pi_musicfest2026_006',
        stripeClientSecret: 'pi_musicfest2026_006_secret_pqr',
        amount: 12000,
        currency: 'USD',
        status: 'succeeded',
        stripeCustomerId: 'cus_music_006',
        stripePaymentMethodId: 'pm_music_006',
        refundedAmount: 0,
        receiptUrl: 'https://stripe.com/receipts/rpt_music_006',
        stripeChargeId: 'ch_music_006',
        lastError: null,
        idempotencyKey: 'idem_music_006',
        webhookProcessedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 12 * 60 * 1000).toISOString(),
        createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000 + 12 * 60 * 1000).toISOString()
    }
];

// Helper to check if we should use mock data
// Mock data is used when:
// 1. USE_MOCK_DATA is explicitly set to 'true', OR
// 2. No DATABASE_URL is provided (app can run without database!)
export const USE_MOCK_DATA = process.env.USE_MOCK_DATA === 'true' || !process.env.DATABASE_URL;

if (USE_MOCK_DATA) {
    console.log('📦 Mock data mode enabled - no database needed!');
    console.log('   To use real database, set DATABASE_URL in .env');
}
