---
# Caddy Handlers

- name: reload caddy
  ansible.builtin.command:
    cmd: docker compose exec caddy caddy reload --config /etc/caddy/Caddyfile
    chdir: "{{ app_base_dir }}"
  become_user: "{{ deploy_user }}"
  become: true
  failed_when: false
  when: caddy_configured | default(false)

- name: restart caddy
  ansible.builtin.command:
    cmd: docker compose restart caddy
    chdir: "{{ app_base_dir }}"
  become_user: "{{ deploy_user }}"
  become: true
  failed_when: false
  when: caddy_configured | default(false)
